version: "2"
services:
  
  web:
    image: nginx:1.11.1
    ports:
      - "9002:80"
    # 先启动php服务，再启动 docker
    depends_on:
      - php
    # 继承php服务数据卷
    volumes_from:
      - php
    volumes:
      - ./images/nginx/config:/etc/nginx/conf.d
  console:
    build:
      context: ./images/console
      dockerfile: Dockerfile
    volumes_from:
      - php
    tty: true
  php:
    build:
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/mnt/app
  db:
      image: mariadb:10.1
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "app"
        MYSQL_USER: "app"
        MYSQL_PASSWORD: "123123"
      volumes:
        - db:/var/lib/mysql
  redis:
    image: redis:3.2.1
    ports:
      - "6379:6379"
volumes:
  db:
    driver: local

